apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: where-for-dinner-ingress
  namespace: wfd-gartner
spec:
  virtualhost:
    fqdn: where-for-dinner.tap-next.blah.cloud
  routes:
  - conditions:
    - prefix: /
    services:
    - name: gateway-where-for-dinner
      port: 80
